# Generated by Django 3.1.7 on 2021-04-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Waiting'), (2, 'In progress'), (4, 'Done')], default=2),
        ),
        migrations.AddField(
            model_name='cart',
            name='status_buy',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
