# Generated by Django 3.1.7 on 2021-04-05 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('image', models.ImageField(blank=True, upload_to='static/images')),
                ('publication_year', models.PositiveSmallIntegerField()),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'available'), (2, 'not available')], default=1)),
                ('rating', models.FloatField(default=0)),
                ('author', models.ManyToManyField(to='warehouse.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Waiting'), (2, 'In progress'), (3, 'Done')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.order')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_status', models.PositiveSmallIntegerField(choices=[(1, 'Reserved'), (2, 'In stock'), (3, 'Sold')], default=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.book')),
                ('item_of_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.orderitem')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.category'),
        ),
    ]
